version: '2'
services:
    gitman-app:
        image: gitman
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://gitman-postgresql:5432/Gitman
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    gitman-postgresql:
        extends:
            file: postgresql.yml
            service: gitman-postgresql
